### ISSUE TITLE
Stop spurious warnings from Replan Central

### ISSUE THREAD

**Issue by jeanconn** [sot/arc#78]
```[tasklist]
### Tasks
- [ ] #77
- [ ] #76
- [ ] #75
- [x] Make a release candidate (this is now 4.8.0)
- [x] Run cron job on the side
- [x] Evaluate cron job logs and outputs to confirm fewer warnings and reasonable outputs for FSDS ticket
- [x] FSDS
- [x] Install
```
